name: Get Bing Today Img

on:
    push:
        branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
    steps:
    - uses: actions/checkout@v3

    - name: commit
      run: | 
        

        git config --global user.email "jrwjb@sina.com"
        git config --global user.name "shubihu"
        git clone https://${ACCESS_TOKEN}@github.com/shubihu/BingTodayImg.git repo
        cp repo/today.png ./

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add today.png
        git commit -m "generated"
        git push
      
